apiVersion: v1
kind: Service
metadata:
  name: {{ include "gcloud-sqlproxy.fullname" . }}
  {{- if .Values.service.internalLB  }}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  {{- end }}
  labels:
    {{- include "gcloud-sqlproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  {{- range $index, $value := .Values.cloudsql.instances }}
  - name: {{ .instanceShortName | default (.instance | trunc 15) }}
    protocol: TCP
    port: {{ .port }}
    {{- if .secure }}
    targetPort: ghostunnel-{{ $index }}
    {{- else }}
    targetPort: {{ .instanceShortName | default (.instance | trunc 15) }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "gcloud-sqlproxy.selectorLabels" . | nindent 4 }}
